site_name: structx
site_description: Structured data extraction from text using LLMs
site_url: https://structx.blacksuan19.dev
site_author: Blacksuan19

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
    logo: material/text-box-search-outline
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.tabs.link
    - toc.follow

repo_url: https://github.com/blacksuan19/structx
repo_name: Blacksuan19/structx
edit_uri: ""

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Examples: examples.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - User Guide:
      - Basic Extraction: guides/basic-extraction.md
      - Custom Models: guides/custom-models.md
      - Unstructured Text: guides/unstructured-text.md
      - Multiple Queries: guides/multiple-queries.md
      - Async Operations: guides/async-operations.md
      - Model Refinements: guides/model-refinement.md
  - API Reference:
      - Extractor: api/extractor.md
      - Models: api/models.md
      - Configuration: api/configuration.md
      - Utilities: api/utilities.md
  - Reference:
      - Supported Formats: reference/supported-formats.md
      - Configuration Options: reference/configuration-options.md
      - Error Handling: reference/error-handling.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            inherited_members: true
            filters:
              - "!^_[^_]" # show all non private members
              - "!^__.*__$" # Exclude all dunder methods
          rendering:
            show_source: true
            show_if_no_docstring: false
            heading_level: 2
            docstring_style: "google"
            docstring_section_style: "table"
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/blacksuan19
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/structx/

copyright: Copyright &copy; 2025 Blacksuan19
