[build-system]
requires = ["setuptools>=45", "wheel", "pip>=21.0"]
build-backend = "setuptools.build_meta"

[project]
name = "structx"
version = "0.1.1"
description = "Structured data extraction from text using LLMs and dynamic model generation"
authors = [{ name = "blacksuan19", email = "py@blacksuan19.dev" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "instructor",
    "openai",
    "pandas",
    "pydantic",
    "PyYAML",
    "tqdm",
    "loguru",
    "omegaconf",
    "litellm",
]

[project.optional-dependencies]
dev = ["black", "bumpver", "pip-tools", "wheel"]


[tool.bumpver]
current_version = "0.1.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true


[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"structx/__init__.py" = ['__version__ = "{version}"']
"README.md" = ["PyPi-{version}"]
